ARG IMAGE_PATH

FROM $IMAGE_PATH

ARG GROUP_ID
ARG GROUP_NAME
ARG USER_ID
ARG USER_NAME

# Add a new user, that maps to host user
RUN groupadd -g $GROUP_ID $GROUP_NAME; useradd -m -u $USER_ID -g $GROUP_ID -G 0 $USER_NAME && \
echo "$USER_NAME ALL=NOPASSWD: ALL" >> /etc/sudoers

# Change to non-root user, but with sudo and capability to execute every command without password
USER $USER_NAME